name: clip
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - conda-forge::cudatoolkit=11.6
  - pytorch::pytorch
  - matplotlib
  - scikit-learn
  - scikit-image
  - pip
  - jupyter
  - kaggle
  - umap-learn
  - altair
  - pandas
  - pip:
    - transformers[torch]
    - datasets
    - praw
